"""
main.py — FastAPI application for the Logistics AI Agent.

Endpoints:
  GET  /                  → Serves the chat UI (index.html)
  POST /query             → Runs the LangChain SQL Agent
  GET  /health            → Health check
  GET  /sample-questions  → Returns example questions for the UI
"""

import os
import time
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from pydantic import BaseModel
from fastapi.concurrency import run_in_threadpool

from database import create_database, DB_PATH
from agent import ask


# Seed the database on startup if it doesn't exist yet
if not os.path.exists(DB_PATH):
    print("📦  First run — creating database…")
    create_database()


# FastAPI app
app = FastAPI(
    title="Logistics AI Agent",
    description="Natural-language querying of logistics data via LangChain + Groq",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# Request / Response models
class QueryRequest(BaseModel):
    question: str


class QueryResponse(BaseModel):
    question: str
    answer: str
    time_taken_s: float


# Routes
@app.get("/", include_in_schema=False)
def serve_ui():
    """Serve the chat frontend."""
    return FileResponse("index.html")


@app.post("/query", response_model=QueryResponse)
async def query_endpoint(body: QueryRequest):
    """
    Main endpoint. Accepts a plain-English question and returns
    an answer generated by the LangChain SQL Agent.
    """
    q = body.question.strip()
    if not q:
        raise HTTPException(status_code=400, detail="Question must not be empty.")
    
    t0 = time.time()
    try:
        # Explicitly offload the blocking LLM call to a thread pool,
        # freeing the FastAPI event loop for other incoming requests
        answer = await run_in_threadpool(ask, q)
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))
    
    return QueryResponse(
        question=q,
        answer=answer,
        time_taken_s=round(time.time() - t0, 2),
    )


@app.get("/health")
def health():
    return {
        "status": "ok",
        "database_exists": os.path.exists(DB_PATH),
        "groq_key_set": bool(os.getenv("GROQ_API_KEY")),
    }


@app.get("/sample-questions")
def sample_questions():
    """Returns pre-written questions shown in the chat UI."""
    return {
        "questions": [
            "Which city had the most delayed orders in the last 30 days?",
            "What is the cancellation rate for each delivery partner?",
            "Which delivery partner has the best on-time delivery rate?",
            "How many orders are currently pending or in transit?",
            "What is the average delivery time by zone (North/South/East/West/Central)?",
            "Which product category gets delayed the most?",
            "Show me the top 5 routes with the highest delay rates",
            "What percentage of orders were delivered on time last week?",
            "Which partner has the highest number of returned orders?",
            "Compare total revenue by city for the last 30 days",
        ]
    }


# Entry point: python main.py
if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
